// Help topics. Also the source of the Builder's Handbook in the vault.
import { LIMITS } from '../script/sandbox.js'

export const HELP_TOPICS = {
  moving: { text: [
    'MOVING AROUND',
    '  north, south, east, west, up, down (or n s e w u d), in, out',
    '  go <exit name>     exits are also named: "tree", "annex", "go to the door"',
    '  exits              list the ways out      home     back to your home room',
    '  @join <player>     go to a friend          @sethome make this room home',
    '  map (m)            the rooms you have seen',
  ] },
  things: { text: [
    'THINGS',
    '  examine <thing> (x)   look closely; books and logbooks open',
    '  read <thing>          read notes, signs, inscriptions',
    '  take <thing>, drop <thing>, put <thing> in <box>, take <thing> from <box>',
    '  open <box>, close <box>, look in <box>',
    '  use <item> [on <thing>]   items from your pack, on their own or on something here',
    '  inventory (i)         what you carry',
    '  write <text> on <note>, erase <note>   for notes and guestbooks',
    'Things built by other visitors often say what you can do with them in parentheses.',
  ] },
  social: { text: [
    'TALKING',
    '  say <text>  or  "text          everyone in the room hears you',
    '  emote <action>  or  :action    "Yourname waves"',
    '  whisper <text> to <player>     private, same room',
    '  page <player> <text>           anywhere; offline players get it as mail',
    '  who                            who is here and where',
    '  mail alex <text>               a letter to Alex — the person who built this',
    '  mail                           read your letters',
    '  think <text>                   ". o O ( ... )"',
    '  @name <name>, @gender <he|she|they|it>, @describe me as "..."',
    '  @register <name> <password>    keep your name (and bit) from any browser; then: connect <name> <password>',
  ] },
  building: { requires: 'programmer', text: [
    'BUILDING  (you have the bit; these work for you)',
    '  @dig north to "Room Name"        a new room with an exit there and back (from a room you own, or The Annex)',
    '  @dig "Room Name"                 a room with no exits yet;  @exit north to #id  connects one',
    '  @describe here as "..."          describe a room or thing;   @describe here   opens the line editor',
    '  @art here                        draw the ASCII art shown above your room',
    '  @create $thing named "Lantern,lamp"     a new thing in your pack ($note, $container, or any example: @classes)',
    '  @rename lamp to "Brass Lantern,lantern"',
    '  @set lamp.lit to true            properties: text, numbers, true/false, JSON',
    '  @set here.private to true        keep others from @joining you there',
    '  @lock north with "brass key"     locks: a thing\'s name, me, programmer, nobody; && || !',
    '  @messages lamp / @take_succeeded lamp is "You lift %t."    custom messages (%N you, %t this, %s %o %p pronouns)',
    '  @recycle lamp                    destroy it;  @audit  lists what you own;  @quota  how many more',
    '  @examine lamp                    the technical view (id, parent, props, verbs)',
    '  @teleport me to #123             to a room of yours;  @go "Room Name"',
    'To make a thing DO something, give it a verb: help scripting.',
    `Quota: ${LIMITS.verbsPerObject} verbs per thing; objects per builder as @quota says. Ask Alex for more: mail alex ...`,
  ] },
  scripting: { requires: 'programmer', text: [
    'SCRIPTING  (verbs are small JavaScript programs attached to things)',
    '  1. @create $thing named "Button,button"',
    '  2. @verb button:push this none none       "push button" — this=the button, no preposition',
    '  3. @program button:push                   then type lines, and "." alone to save:',
    '       tell(player, "Click.")',
    '       announce(player.name + " pushes the button.")',
    '       this.presses = (this.presses || 0) + 1',
    '       .',
    '  4. push button',
    '',
    '  @edit button:push        the same, in an editor window    @list button:push   read any readable verb',
    '  @args button:push any on this   change what the verb expects: "put coin on button" is  any on this',
    '  @test button:push        dry run: shows what it would do without doing it',
    '  ;here.name               evaluate one line (";" prefix);  ;contents(here).map(o => o.name)',
    '  @tasks / @kill           timers made with fork()',
    '',
    'Arg specs: "this" = this thing must be named there, "any" = anything, "none" = nothing.',
    '  push button              this none none        put coin in slot     any in this',
    '  give rock to parrot      any to this           sing                 none none none (works on anything in the room)',
    '  tick                     this none this        not a command: only fork("tick") or call() can run it',
    '',
    'Inside a verb you have: this, player, here, dobj, iobj, args, argstr, dobjstr, prepstr, iobjstr',
    `Limits: ${LIMITS.cpuMs}ms of CPU per run, ${LIMITS.codeBytes} characters per verb, ${LIMITS.maxEffects} changes per run. If it crashes, nothing is changed and you are told why.`,
    'Everything you can call: help api.  Worked examples you can copy: help examples.',
  ] },
  api: { requires: 'programmer', text: [
    'SCRIPT API',
    '  OBJECTS  (this, player, here, dobj, iobj, or obj("#12"))',
    '    o.name  o.description  o.location  o.contents  o.owner  o.parent  o.kind  o.id',
    '    o.anyProp = value          saved when the verb finishes (your things, or things with +w)',
    '    o.tell(text)  o.announce(text)  o.move(place)  o.has("prop")  o.is(other)  o.exits (rooms)',
    '    player.name  player.programmer  player.online   (other players\' props are private)',
    '  OUTPUT',
    '    tell(who, text)                 to one player',
    '    announce(text, {except, room, all})   to the room (by default everyone but player; all:true includes them)',
    '    sub("%N pets %t", thing)        pronoun substitution: %N player %t this %s/%o/%p pronouns %<verb> agreement',
    '  WORLD',
    '    move(thing, place)              places: rooms, players (packs), containers. Players can be moved only by verbs they triggered, or from rooms you own.',
    '    create(name, {parent, description, aliases, where})   new thing (counts toward your quota)',
    '    recycle(thing)   find("rock")   find("rock", box)   contents(box)   players(here)   roomOf(thing)   locked(thing)',
    '  TIME',
    '    fork(seconds, "verbname", ...args)   run this thing\'s verb later (survives restarts)',
    '    every(seconds, "verbname")           repeat (min 10s)     cancel("verbname")',
    '    now()  — milliseconds',
    '  HELPERS',
    '    random(n)  random(a, b)  pick(array)  cap(text)  list(array)  name(thing)  log(text) — debug line to you',
    '    call(thing, "verb", ...args)       run another verb (depth 5)',
    '  CONTROL',
    '    return false                       "not handled": the built-in command runs instead',
    '  JavaScript: Math, JSON, String, Array, Date, RegExp all work. No fetch, no require, no setTimeout (use fork).',
  ] },
  examples: { requires: 'programmer', text: [
    'EXAMPLES  (in The Annex, east of the Workshop; all readable with @list, all fertile)',
    '  $pet_rock   pet / feed / throw        messages customised with @set rock.pet_msg',
    '  $button     push + a 10s timer        fork(10, "lamp_off") and cancel()',
    '  $dice       roll                      random()',
    '  $sign       read                      a scripted verb replacing a built-in for one thing',
    '  $lever      pull                      one object controlling another (an exit\'s lock)',
    '  $computer   type <text> on computer   shared state everyone can read',
    '  $vehicle    enter, pilot north        a thing players ride between rooms',
    '  $monster    attack                    hit points, per-player scores, respawn timer — the seed of an RPG',
    '  $npc        talk to / ask about       keyword replies',
    '  $note, $container                     built in: write/read/erase, put/take/open/close',
    'Copy one:   @create $monster named "Cave Troll,troll"     then  @set troll.maxhp to 50',
    'Read one:   @list $vehicle:pilot          Change a copy:  @copy $vehicle:pilot to mine:pilot  then @edit mine:pilot',
    'Build a quest: a locked exit (@lock), a key (any thing named in the lock), a $npc who hints, a $monster that drops the key:',
    '    in the monster\'s attack verb, when hp hits 0:   move(create("Rusty Key", {description: "A key."}), player)',
  ] },
  messages: { requires: 'programmer', text: [
    'MESSAGES  (what people see; set with @<name> <thing> is "text")',
    '  exits:      @leave @oleave @arrive @oarrive @nogo @onogo       e.g. @oarrive north is "%N arrives in a shower of sparks."',
    '  things:     @take_succeeded @otake_succeeded @take_failed @drop_succeeded @odrop_succeeded ...',
    '  containers: @open @oopen @close @oclose @put @oput @put_fail @open_fail',
    '  vehicles:   @enter @oenter @exit @oexit',
    '  "o" messages are what everyone else sees; %N is the actor, %t the thing, %s/%o/%p/%r pronouns, %<verb> agrees with the pronoun.',
  ] },
  locks: { requires: 'programmer', text: [
    'LOCKS   @lock <exit|thing|box> with <key>',
    '  key = a thing\'s name ("brass key"): the player must be, or carry, it',
    '  me          only you        programmer   anyone with the bit      nobody   no one',
    '  a && b      both            a || b       either                   !a       not',
    '  flag:xyz    players who have the house flag xyz (seed puzzles)',
    '  @nogo exit is "The door is barred."      what the locked-out see',
  ] },
  narrator: { text: [
    'THE NARRATOR',
    'Anything the house does not understand goes to the narrator, who describes, answers, and sometimes does what you meant',
    '("walk through the eastern door" becomes "east"). The narrator cannot invent rooms or items; it only narrates what is really here.',
  ] },
  vault: { requires: 'wizard', text: ['The vault chain: compass in the hall → gear → crystal → down → tome on the black door → down → take bit.'] },
}

// The handbook in the vault, as logbook pages.
export function handbookPages() {
  const page = (title, body) => ({ title, body })
  return [
    page('The Bit', 'You hold the programmer bit. It means this house will let you add to it. Rooms, things, little machines, whole games. Everything you make stays, and everyone who comes after can find it.'),
    page('First Room', 'Go to The Annex (east of the Workshop). Type:   @dig north to "The Lantern Room"   Then: north, and   @describe here as "A small room full of lamps."   That is a room. It is already real.'),
    page('First Thing', '@create $thing named "Brass Lamp,lamp"   puts a lamp in your pack. @describe lamp as "..."   Drop it in your room. Anyone can examine it now.'),
    page('First Verb', '@verb lamp:light this none none   then   @program lamp:light   and type:\n  tell(player, "The lamp glows.")\n  announce(player.name + " lights the lamp.")\n  this.lit = true\n  .\nNow "light lamp" works for everyone.'),
    page('Learning More', 'In the terminal: help building, help scripting, help api, help examples. The things on the Annex bench are examples you can @list and copy. Stuck? mail alex <question>.'),
    page('The Rules', 'Be kind. What you build is yours; what others build is theirs. The house keeps a quota so no one can fill it alone. Alex can see everything and will fix what breaks. Finish what you start, build for the public, avoid tiny scenery, be original.'),
  ]
}
